# Generated by Django 6.0.2 on 2026-02-10 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JenisPekerjaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_pekerjaan",
                    models.CharField(max_length=100, verbose_name="Nama Pekerjaan"),
                ),
                (
                    "file_path",
                    models.FileField(
                        upload_to="pekerjaan/tipe/", verbose_name="Icon/Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Jenis Pekerjaan",
                "verbose_name_plural": "Jenis Pekerjaan",
                "db_table": "jenis_pekerjaan",
            },
        ),
        migrations.CreateModel(
            name="Lowongan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_perusahaan",
                    models.CharField(max_length=100, verbose_name="Nama Perusahaan"),
                ),
                ("kuota", models.IntegerField(verbose_name="Kuota")),
                (
                    "batas_bawah_usia",
                    models.IntegerField(verbose_name="Batas Bawah Usia"),
                ),
                (
                    "batas_atas_usia",
                    models.IntegerField(verbose_name="Batas Atas Usia"),
                ),
                (
                    "lokasi_kerja",
                    models.CharField(max_length=50, verbose_name="Lokasi Kerja"),
                ),
                (
                    "deskripsi_pekerjaan",
                    models.TextField(
                        blank=True, null=True, verbose_name="Deskripsi Pekerjaan"
                    ),
                ),
                ("batas_lamar", models.DateField(verbose_name="Batas Lamar")),
                ("is_active", models.BooleanField(verbose_name="Aktif")),
                ("created_at", models.DateTimeField(verbose_name="Tanggal Dibuat")),
                ("updated_at", models.DateTimeField(verbose_name="Tanggal Diupdate")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dibuat_oleh",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat oleh",
                    ),
                ),
                (
                    "jenis_pekerjaan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lowongan",
                        to="jobs.jenispekerjaan",
                        verbose_name="Jenis Pekerjaan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diupdate_oleh",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diupdate oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lowongan",
                "verbose_name_plural": "Lowongan",
                "db_table": "lowongan",
            },
        ),
        migrations.CreateModel(
            name="Persyaratan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Persyaratan")),
                (
                    "lowongan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.lowongan",
                        verbose_name="Lowongan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persyaratan",
                "verbose_name_plural": "Persyaratan",
                "db_table": "persyaratan",
            },
        ),
    ]
