# Generated by Django 6.0.2 on 2026-02-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lowongan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Tanggal Dibuat"
            ),
        ),
        migrations.AlterField(
            model_name="lowongan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Tanggal Diupdate"),
        ),
    ]
