# Generated by Django 6.0.2 on 2026-02-13 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_lowongan_created_at_alter_lowongan_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persyaratan",
            name="lowongan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persyaratan",
                to="jobs.lowongan",
                verbose_name="Lowongan",
            ),
        ),
    ]
