# Generated by Django 6.0.2 on 2026-02-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_persyaratan_lowongan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jenispekerjaan",
            name="file_path",
            field=models.FileField(
                blank=True, upload_to="pekerjaan/tipe/", verbose_name="Icon/Image"
            ),
        ),
    ]
