# Generated by Django 6.0.2 on 2026-02-10 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("participants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lamaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_lamaran",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Direview", "Direview"),
                            ("Terdaftar", "Terdaftar"),
                            ("Mendan 1", "Mendan 1"),
                            ("Mendan 2", "Mendan 2"),
                            ("Mensetsu", "Mensetsu"),
                            ("GOUKAKU", "GOUKAKU"),
                            ("FU GOKAKU", "FU GOUKAKU"),
                        ],
                        default="Pending",
                        max_length=50,
                        verbose_name="Status Lamaran",
                    ),
                ),
                ("catatan", models.TextField(verbose_name="Catatan")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Tanggal Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Tanggal Diupdate"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lamaran_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
                (
                    "lowongan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lamaran",
                        to="jobs.lowongan",
                        verbose_name="Lowongan",
                    ),
                ),
                (
                    "peserta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lamaran",
                        to="participants.peserta",
                        verbose_name="Peserta",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lamaran_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diupdate Oleh",
                    ),
                ),
            ],
        ),
    ]
