# Generated by Django 6.0.3 on 2026-03-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamaran',
            name='status_lamaran',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Direview', 'Direview'), ('Terdaftar', 'Terdaftar'), ('Mendan 1', 'Mendan 1'), ('Mendan 2', 'Mendan 2'), ('Mensetsu', 'Mensetsu'), ('Goukaku', 'Goukaku'), ('Fu Goukaku', 'Fu Goukaku')], default='Pending', max_length=50, verbose_name='Status Lamaran'),
        ),
    ]
