# Generated by Django 6.0.2 on 2026-02-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
    ]
