# Generated by Django 6.0.2 on 2026-02-10 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Peserta",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="peserta_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nama_lengkap",
                    models.CharField(max_length=50, verbose_name="Nama Lengkap"),
                ),
                (
                    "nama_lengkap_katakana",
                    models.CharField(
                        max_length=50, verbose_name="Nama Lengkap (Katakana)"
                    ),
                ),
                ("tanggal_lahir", models.DateField(verbose_name="Tanggal Lahir")),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[
                            ("Laki-laki", "Laki-laki"),
                            ("Perempuan", "Perempuan"),
                        ],
                        max_length=50,
                        verbose_name="Jenis Kelamin",
                    ),
                ),
                (
                    "agama",
                    models.CharField(
                        choices=[
                            ("Islam", "Islam"),
                            ("Kristen", "Kristen"),
                            ("Katolik", "Katolik"),
                            ("Hindu", "Hindu"),
                            ("Buddha", "Buddha"),
                            ("Konghucu", "Konghucu"),
                        ],
                        max_length=50,
                        verbose_name="Agama",
                    ),
                ),
                ("nomor_hp", models.CharField(max_length=50, verbose_name="Nomor HP")),
                (
                    "status_pernikahan",
                    models.CharField(
                        choices=[
                            ("LAJANG", "LAJANG"),
                            ("Menikah", "Menikah"),
                            ("Cerai Mati", "Cerai Mati"),
                            ("Cerai Hidup", "Cerai Hidup"),
                        ],
                        max_length=50,
                        verbose_name="Status Pernikahan",
                    ),
                ),
                ("alamat_ktp", models.TextField(verbose_name="Alamat KTP")),
                ("alamat_domisili", models.TextField(verbose_name="Alamat Domisili")),
                (
                    "minat_program",
                    models.CharField(max_length=50, verbose_name="Minat Program"),
                ),
                (
                    "pengalaman_ke_jepang",
                    models.TextField(verbose_name="Pengalaman ke Jepang"),
                ),
                ("tujuan_ke_jepang", models.TextField(verbose_name="Tujuan ke Jepang")),
                (
                    "penghasilan_keluarga",
                    models.IntegerField(verbose_name="Penghasilan Keluarga"),
                ),
                (
                    "target_penabungan",
                    models.IntegerField(verbose_name="Target Penabungan"),
                ),
                ("berat_badan", models.IntegerField(verbose_name="Berat Badan (kg)")),
                ("tinggi_badan", models.IntegerField(verbose_name="Tinggi Badan (cm)")),
                ("cek_mata_kanan", models.FloatField(verbose_name="Cek Mata Kanan")),
                ("cek_mata_kiri", models.FloatField(verbose_name="Cek Mata Kiri")),
                (
                    "golongan_darah",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("AB", "AB"), ("O", "O")],
                        max_length=50,
                        verbose_name="Golongan Darah",
                    ),
                ),
                (
                    "tangan_dominan",
                    models.CharField(
                        choices=[("Kanan", "Kanan"), ("Kiri", "Kiri")],
                        max_length=50,
                        verbose_name="Tangan Dominan",
                    ),
                ),
                ("alergi_makanan", models.TextField(verbose_name="Alergi Makanan")),
                (
                    "pantangan_makanan",
                    models.TextField(verbose_name="Pantangan Makanan"),
                ),
                ("riwayat_penyakit", models.TextField(verbose_name="Riwayat Penyakit")),
                ("kelebihan", models.TextField(verbose_name="Kelebihan")),
                ("kekurangan", models.TextField(verbose_name="Kekurangan")),
                ("hobi", models.TextField(verbose_name="Hobi")),
                (
                    "status_validasi",
                    models.CharField(
                        choices=[
                            ("Diajukan", "Menunggu Validasi"),
                            ("Validasi 1", "Validasi 1"),
                            ("Validasi 2", "Validasi 2"),
                            ("Approved", "Approved"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Diajukan",
                        verbose_name="Status Validasi",
                    ),
                ),
                (
                    "validasi_1_pada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Validasi 1"
                    ),
                ),
                (
                    "validasi_1_notes",
                    models.TextField(blank=True, verbose_name="Catatan Validasi 1"),
                ),
                (
                    "validasi_2_pada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Validasi 2"
                    ),
                ),
                (
                    "validasi_2_notes",
                    models.TextField(blank=True, verbose_name="Catatan Validasi 2"),
                ),
                (
                    "tervalidasi_pada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Approved"
                    ),
                ),
                (
                    "alasan_penolakan",
                    models.TextField(blank=True, verbose_name="Alasan Ditolak"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Dibuat"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Tanggal Diupdate"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_peserta_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diupdate Oleh",
                    ),
                ),
                (
                    "validasi_1_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_peserta_level_1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Divalidasi 1 Oleh",
                    ),
                ),
                (
                    "validasi_2_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_peserta_level_2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Divalidasi 2 Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peserta",
                "verbose_name_plural": "Peserta",
                "db_table": "peserta",
            },
        ),
        migrations.CreateModel(
            name="DokumenPeserta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jenis_dokumen",
                    models.CharField(
                        choices=[
                            ("JLPT", "JLPT"),
                            ("JFT", "JFT"),
                            ("SSW", "SSW"),
                            ("JITCO", "JITCO"),
                        ],
                        max_length=50,
                        verbose_name="Jenis Dokumen",
                    ),
                ),
                (
                    "nama_dokumen",
                    models.CharField(max_length=50, verbose_name="Nama Dokumen"),
                ),
                (
                    "file_path",
                    models.FileField(
                        upload_to="peserta/dokumen/%Y/%m/", verbose_name="File"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "peserta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokumen",
                        to="participants.peserta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumen Peserta",
                "verbose_name_plural": "Dokumen Peserta",
                "db_table": "dokumen_peserta",
            },
        ),
        migrations.CreateModel(
            name="DataKeluarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hubungan_keluarga",
                    models.CharField(
                        choices=[
                            ("Ayah", "Ayah"),
                            ("Ibu", "Ibu"),
                            ("Suami", "Suami"),
                            ("Istri", "Istri"),
                            ("Anak", "Anak"),
                            ("Kakak", "Kakak"),
                            ("Adik", "Adik"),
                            ("Saudara", "Saudara"),
                        ],
                        max_length=50,
                        verbose_name="Hubungan Keluarga",
                    ),
                ),
                ("tanggal_lahir", models.DateField(verbose_name="Tanggal Lahir")),
                (
                    "pekerjaan",
                    models.CharField(max_length=50, verbose_name="Pekerjaan"),
                ),
                (
                    "peserta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_keluarga",
                        to="participants.peserta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Keluarga",
                "verbose_name_plural": "Data Keluarga",
                "db_table": "data_keluarga",
            },
        ),
        migrations.CreateModel(
            name="RiwayatPekerjaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_perusahaan",
                    models.CharField(max_length=100, verbose_name="Nama Perusahaan"),
                ),
                (
                    "bidang_usaha",
                    models.CharField(max_length=100, verbose_name="Bidang Usaha"),
                ),
                ("jabatan", models.CharField(max_length=50, verbose_name="Jabatan")),
                ("gaji", models.IntegerField(verbose_name="Gaji")),
                ("tanggal_masuk", models.DateField(verbose_name="Tanggal Masuk")),
                ("tanggal_keluar", models.DateField(verbose_name="Tanggal Keluar")),
                (
                    "peserta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riwayat_pekerjaan",
                        to="participants.peserta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Riwayat Pekerjaan",
                "db_table": "riwayat_pekerjaan",
                "ordering": ["-tanggal_masuk"],
            },
        ),
        migrations.CreateModel(
            name="RiwayatPendidikan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jenjang",
                    models.CharField(
                        choices=[
                            ("Sekolah Dasar", "SD"),
                            ("Sekolah Menengah Pertama", "SMP"),
                            ("Sekolah Menengah Atas", "SMA"),
                            ("Sekolah Menengah Kejuruan", "SMK"),
                            ("Diploma 3", "D3"),
                            ("Sarjana", "S1"),
                            ("Magister", "S2"),
                            ("Doktor", "S3"),
                        ],
                        max_length=50,
                        verbose_name="Jenjang",
                    ),
                ),
                (
                    "nama_institusi",
                    models.CharField(max_length=100, verbose_name="Nama Institusi"),
                ),
                ("tahun_masuk", models.DateField(verbose_name="Tahun Masuk")),
                ("tahun_lulus", models.DateField(verbose_name="Tahun Keluar")),
                (
                    "peserta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riwayat_pendidikan",
                        to="participants.peserta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riwayat Pendidikan",
                "verbose_name_plural": "Riwayat Pendidikan",
                "db_table": "riwayat_pendidikan",
                "ordering": ["-tahun_lulus"],
            },
        ),
    ]
