# Generated by Django 6.0.2 on 2026-02-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peserta",
            name="status_validasi",
            field=models.CharField(
                choices=[
                    ("Diajukan", "Menunggu Validasi"),
                    ("Validasi 1", "Validasi 1"),
                    ("Validasi 2", "Validasi 2"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Suspended", "Suspended"),
                ],
                default="Diajukan",
                verbose_name="Status Validasi",
            ),
        ),
    ]
