# Generated by Django 6.0.2 on 2026-04-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0002_alter_peserta_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peserta",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Tanggal Dibuat"
            ),
        ),
    ]
