# Generated by Django 6.0.2 on 2026-02-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0002_alter_peserta_status_validasi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dokumenpeserta",
            name="jenis_dokumen",
            field=models.CharField(
                choices=[
                    ("JLPT", "JLPT"),
                    ("JFT", "JFT"),
                    ("SSW", "SSW"),
                    ("JITCO", "JITCO"),
                    ("FOTO PROFIL", "FOTO PROFIL"),
                ],
                max_length=50,
                verbose_name="Jenis Dokumen",
            ),
        ),
        migrations.AlterField(
            model_name="peserta",
            name="status_validasi",
            field=models.CharField(
                choices=[
                    ("Diajukan", "Menunggu Validasi"),
                    ("Validasi 1", "Validasi 1"),
                    ("Validasi 2", "Validasi 2"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Suspended", "Suspended"),
                ],
                db_index=True,
                default="Diajukan",
                verbose_name="Status Validasi",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="riwayatpendidikan",
            unique_together={("peserta", "jenjang", "nama_institusi")},
        ),
    ]
