# Generated by Django 6.0.2 on 2026-02-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0003_alter_dokumenpeserta_jenis_dokumen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peserta",
            name="status_pernikahan",
            field=models.CharField(
                choices=[
                    ("Lajang", "Lajang"),
                    ("Menikah", "Menikah"),
                    ("Cerai Mati", "Cerai Mati"),
                    ("Cerai Hidup", "Cerai Hidup"),
                ],
                max_length=50,
                verbose_name="Status Pernikahan",
            ),
        ),
    ]
