# Generated by Django 6.0.2 on 2026-04-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0003_alter_peserta_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peserta",
            name="status_validasi",
            field=models.CharField(
                choices=[
                    ("Diajukan", "Menunggu Validasi"),
                    ("Validasi 1", "Validasi 1"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Suspended", "Suspended"),
                ],
                db_index=True,
                default="Diajukan",
                verbose_name="Status Validasi",
            ),
        ),
    ]
