# Generated by Django 6.0.3 on 2026-03-26 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_alter_peserta_status_pernikahan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='agama',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Konghucu', 'Konghucu')], max_length=50, verbose_name='Agama'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='alamat_domisili',
            field=models.TextField(blank=True, verbose_name='Alamat Domisili'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='alamat_ktp',
            field=models.TextField(blank=True, verbose_name='Alamat KTP'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='alergi_makanan',
            field=models.TextField(blank=True, verbose_name='Alergi Makanan'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='berat_badan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Berat Badan (kg)'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='cek_mata_kanan',
            field=models.FloatField(blank=True, null=True, verbose_name='Cek Mata Kanan'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='cek_mata_kiri',
            field=models.FloatField(blank=True, null=True, verbose_name='Cek Mata Kiri'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='golongan_darah',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=50, verbose_name='Golongan Darah'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='hobi',
            field=models.TextField(blank=True, verbose_name='Hobi'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=50, verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='kekurangan',
            field=models.TextField(blank=True, verbose_name='Kekurangan'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='kelebihan',
            field=models.TextField(blank=True, verbose_name='Kelebihan'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='minat_program',
            field=models.CharField(blank=True, max_length=50, verbose_name='Minat Program'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nama_lengkap_katakana',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nama Lengkap (Katakana)'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nomor_hp',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nomor HP'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='pantangan_makanan',
            field=models.TextField(blank=True, verbose_name='Pantangan Makanan'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='pengalaman_ke_jepang',
            field=models.TextField(blank=True, verbose_name='Pengalaman ke Jepang'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='penghasilan_keluarga',
            field=models.IntegerField(blank=True, null=True, verbose_name='Penghasilan Keluarga'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='riwayat_penyakit',
            field=models.TextField(blank=True, verbose_name='Riwayat Penyakit'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='status_pernikahan',
            field=models.CharField(blank=True, choices=[('Lajang', 'Lajang'), ('Menikah', 'Menikah'), ('Cerai Mati', 'Cerai Mati'), ('Cerai Hidup', 'Cerai Hidup')], max_length=50, verbose_name='Status Pernikahan'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='tangan_dominan',
            field=models.CharField(blank=True, choices=[('Kanan', 'Kanan'), ('Kiri', 'Kiri')], max_length=50, verbose_name='Tangan Dominan'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='target_penabungan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Target Penabungan'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='tinggi_badan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tinggi Badan (cm)'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='tujuan_ke_jepang',
            field=models.TextField(blank=True, verbose_name='Tujuan ke Jepang'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_peserta_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='validasi_1_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_peserta_level_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='validasi_2_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_peserta_level_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
